spring:
  application:
    name: item-service  
  cloud:
    config:
      override-none: true
  rabbitmq:
    host: 10.211.55.6
    port: 5672
    username: admin
    password: admin      
      
server:
  port: 8001
  
eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka, http://eureka2:2002/eureka

